name: event_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  sliver_tools: ^0.2.10
  google_nav_bar: ^5.0.6
  get: ^4.6.5
  google_fonts: ^4.0.3
  icons_plus: ^4.0.0
  carousel_slider: ^4.2.1
  flutter_easyloading: ^3.0.5
  flutter_displaymode: ^0.5.0
  lottie: ^1.3.0
  icons_animate: ^0.0.2
  speed_dial_fab: ^2.3.0
  # intl: ^0.18.1
  cached_network_image: ^3.2.3
  image_picker: ^0.8.7+4
  image_picker_android: ^0.8.6+7
  time: ^2.1.3
  image_editor: ^1.3.0
  # flutter_animated_icons: ^1.0.1

  # Firebase 
  firebase_auth: ^4.4.1
  firebase_core: ^2.9.0
  firebase_storage: ^11.1.0
  cloud_firestore: ^4.5.1


 
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
